### ISSUE TITLE
Need Large File Support

### ISSUE THREAD

**Issue by richas32** [JetBrains/ideolog#129]
There isn't a log file worth its salt under 10 MB.  This kept saying it wouldn't support files over 2.56 MB.  Its worthless if that is the case.  If its not you need to add a Max Size that actually means something.  I tried upping the edit file size support and it would only go to 2.56 MB regardless of what I put in.

**Comment by Ararem** [comment]
@richas32 I've found a solution for this. Mine is using Rider 2022.2.1, but should be the same process for you

Go to `Help > Edit Custom Properties`
![Image of me selecting Edit Custom Properties](https://user-images.githubusercontent.com/48875125/185519674-27336591-081a-4992-b4bc-4ac207efa6c0.png)

This should open a file called `idea.properties`. Mine was empty:
```
# custom JetBrains Rider properties (expand/override 'bin\idea.properties')

```

The property we want to edit is the max filesize (`idea.max.intellisense.filesize`), so we add the line to the file:
`idea.max.intellisense.filesize=10000`. Note that there's some weird number things going on, since `2500` should be `2500kB` or `2.5MB`, but it gets translated as `2.56MB` (x1.024), so this will slightly affect it. If you want a limit of 10MB, then just use `10000` as this should be enough. I used `25MB` for mine, leaving my final file like this:
```
# custom JetBrains Rider properties (expand/override 'bin\idea.properties')

idea.max.intellisense.filesize=25000
```

You'll have to restart the IDE after changing the file to make the changes apply (`File > Invalidate Caches > Invalidate and Restart`)

Hope this fixed it for you (did it for me)!

**Comment by smirok** [comment]
Hi! We have recently added support for large files (> 20 MB): we provide highlighting and navigation with hyperlinks for large files.
